# Generated by Django 3.1 on 2021-03-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20210315_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
