# Generated by Django 3.1 on 2021-03-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_auto_20210317_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, to='studentapp.ClassRoom'),
        ),
    ]
