# Generated by Django 3.1 on 2021-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_auto_20210317_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, default='student', max_length=200, null=True),
        ),
    ]
